version: "3"

services:
  mysql:
    container_name: attendanceApp_mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'attendance'
      MYSQL_PASSWORD: 'root'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/mysql/init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql\

volumes:
  db-data:
    driver: local